import type { NextPage } from "next";
import Head from "next/head";
import styles from "@shared/styles/Home.module.css";
import UserAuthentication from "@userAuthentication/UserAuthentication";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to co-todolist</h1>
        <UserAuthentication />
      </main>
    </div>
  );
};

export default Home;
